# Generated by Django 6.0 on 2026-01-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
